apiVersion: ctlptl.dev/v1alpha1
kind: Registry
port: 5004
listenAddress: 127.0.0.1
---
apiVersion: ctlptl.dev/v1alpha1 # # https://pkg.go.dev/sigs.k8s.io/kind/pkg/apis/config/v1alpha4#Cluster
kind: Cluster
product: kind
registry: ctlptl-registry
kindV1Alpha4Cluster:
  name: kind
  nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      - containerPort: 8001
        hostPort: 8001
        protocol: TCP
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP